In [1]:
import numpy as np
import pandas as pd
import datetime
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
import nfl_data_py as nfl

# Load NFL data for a specific range of years
data = nfl.import_pbp_data(range(2001, 2023))

# Print information about the DataFrame, including column names and data types
print(data.info())

2001 done.
2002 done.
2003 done.
2004 done.
2005 done.
2006 done.
2007 done.
2008 done.
2009 done.
2010 done.
2011 done.
2012 done.
2013 done.
2014 done.
2015 done.
2016 done.
2017 done.
2018 done.
2019 done.
2020 done.
2021 done.
2022 done.
Downcasting floats.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1057089 entries, 0 to 1057088
Columns: 384 entries, play_id to n_defense
dtypes: float32(204), int32(6), int64(1), object(173)
memory usage: 2.2+ GB
None

In [3]:
data.columns.values

array(['play_id', 'game_id', 'old_game_id', 'home_team', 'away_team',
       'season_type', 'week', 'posteam', 'posteam_type', 'defteam',
       'side_of_field', 'yardline_100', 'game_date',
       'quarter_seconds_remaining', 'half_seconds_remaining',
       'game_seconds_remaining', 'game_half', 'quarter_end', 'drive',
       'sp', 'qtr', 'down', 'goal_to_go', 'time', 'yrdln', 'ydstogo',
       'ydsnet', 'desc', 'play_type', 'yards_gained', 'shotgun',
       'no_huddle', 'qb_dropback', 'qb_kneel', 'qb_spike', 'qb_scramble',
       'pass_length', 'pass_location', 'air_yards', 'yards_after_catch',
       'run_location', 'run_gap', 'field_goal_result', 'kick_distance',
       'extra_point_result', 'two_point_conv_result',
       'home_timeouts_remaining', 'away_timeouts_remaining', 'timeout',
       'timeout_team', 'td_team', 'td_player_name', 'td_player_id',
       'posteam_timeouts_remaining', 'defteam_timeouts_remaining',
       'total_home_score', 'total_away_score', 'posteam_score',
       'defteam_score', 'score_differential', 'posteam_score_post',
       'defteam_score_post', 'score_differential_post', 'no_score_prob',
       'opp_fg_prob', 'opp_safety_prob', 'opp_td_prob', 'fg_prob',
       'safety_prob', 'td_prob', 'extra_point_prob',
       'two_point_conversion_prob', 'ep', 'epa', 'total_home_epa',
       'total_away_epa', 'total_home_rush_epa', 'total_away_rush_epa',
       'total_home_pass_epa', 'total_away_pass_epa', 'air_epa', 'yac_epa',
       'comp_air_epa', 'comp_yac_epa', 'total_home_comp_air_epa',
       'total_away_comp_air_epa', 'total_home_comp_yac_epa',
       'total_away_comp_yac_epa', 'total_home_raw_air_epa',
       'total_away_raw_air_epa', 'total_home_raw_yac_epa',
       'total_away_raw_yac_epa', 'wp', 'def_wp', 'home_wp', 'away_wp',
       'wpa', 'vegas_wpa', 'vegas_home_wpa', 'home_wp_post',
       'away_wp_post', 'vegas_wp', 'vegas_home_wp', 'total_home_rush_wpa',
       'total_away_rush_wpa', 'total_home_pass_wpa',
       'total_away_pass_wpa', 'air_wpa', 'yac_wpa', 'comp_air_wpa',
       'comp_yac_wpa', 'total_home_comp_air_wpa',
       'total_away_comp_air_wpa', 'total_home_comp_yac_wpa',
       'total_away_comp_yac_wpa', 'total_home_raw_air_wpa',
       'total_away_raw_air_wpa', 'total_home_raw_yac_wpa',
       'total_away_raw_yac_wpa', 'punt_blocked', 'first_down_rush',
       'first_down_pass', 'first_down_penalty', 'third_down_converted',
       'third_down_failed', 'fourth_down_converted', 'fourth_down_failed',
       'incomplete_pass', 'touchback', 'interception',
       'punt_inside_twenty', 'punt_in_endzone', 'punt_out_of_bounds',
       'punt_downed', 'punt_fair_catch', 'kickoff_inside_twenty',
       'kickoff_in_endzone', 'kickoff_out_of_bounds', 'kickoff_downed',
       'kickoff_fair_catch', 'fumble_forced', 'fumble_not_forced',
       'fumble_out_of_bounds', 'solo_tackle', 'safety', 'penalty',
       'tackled_for_loss', 'fumble_lost', 'own_kickoff_recovery',
       'own_kickoff_recovery_td', 'qb_hit', 'rush_attempt',
       'pass_attempt', 'sack', 'touchdown', 'pass_touchdown',
       'rush_touchdown', 'return_touchdown', 'extra_point_attempt',
       'two_point_attempt', 'field_goal_attempt', 'kickoff_attempt',
       'punt_attempt', 'fumble', 'complete_pass', 'assist_tackle',
       'lateral_reception', 'lateral_rush', 'lateral_return',
       'lateral_recovery', 'passer_player_id', 'passer_player_name',
       'passing_yards', 'receiver_player_id', 'receiver_player_name',
       'receiving_yards', 'rusher_player_id', 'rusher_player_name',
       'rushing_yards', 'lateral_receiver_player_id',
       'lateral_receiver_player_name', 'lateral_receiving_yards',
       'lateral_rusher_player_id', 'lateral_rusher_player_name',
       'lateral_rushing_yards', 'lateral_sack_player_id',
       'lateral_sack_player_name', 'interception_player_id',
       'interception_player_name', 'lateral_interception_player_id',
       'lateral_interception_player_name', 'punt_returner_player_id',
       'punt_returner_player_name', 'lateral_punt_returner_player_id',
       'lateral_punt_returner_player_name',
       'kickoff_returner_player_name', 'kickoff_returner_player_id',
       'lateral_kickoff_returner_player_id',
       'lateral_kickoff_returner_player_name', 'punter_player_id',
       'punter_player_name', 'kicker_player_name', 'kicker_player_id',
       'own_kickoff_recovery_player_id',
       'own_kickoff_recovery_player_name', 'blocked_player_id',
       'blocked_player_name', 'tackle_for_loss_1_player_id',
       'tackle_for_loss_1_player_name', 'tackle_for_loss_2_player_id',
       'tackle_for_loss_2_player_name', 'qb_hit_1_player_id',
       'qb_hit_1_player_name', 'qb_hit_2_player_id',
       'qb_hit_2_player_name', 'forced_fumble_player_1_team',
       'forced_fumble_player_1_player_id',
       'forced_fumble_player_1_player_name',
       'forced_fumble_player_2_team', 'forced_fumble_player_2_player_id',
       'forced_fumble_player_2_player_name', 'solo_tackle_1_team',
       'solo_tackle_2_team', 'solo_tackle_1_player_id',
       'solo_tackle_2_player_id', 'solo_tackle_1_player_name',
       'solo_tackle_2_player_name', 'assist_tackle_1_player_id',
       'assist_tackle_1_player_name', 'assist_tackle_1_team',
       'assist_tackle_2_player_id', 'assist_tackle_2_player_name',
       'assist_tackle_2_team', 'assist_tackle_3_player_id',
       'assist_tackle_3_player_name', 'assist_tackle_3_team',
       'assist_tackle_4_player_id', 'assist_tackle_4_player_name',
       'assist_tackle_4_team', 'tackle_with_assist',
       'tackle_with_assist_1_player_id',
       'tackle_with_assist_1_player_name', 'tackle_with_assist_1_team',
       'tackle_with_assist_2_player_id',
       'tackle_with_assist_2_player_name', 'tackle_with_assist_2_team',
       'pass_defense_1_player_id', 'pass_defense_1_player_name',
       'pass_defense_2_player_id', 'pass_defense_2_player_name',
       'fumbled_1_team', 'fumbled_1_player_id', 'fumbled_1_player_name',
       'fumbled_2_player_id', 'fumbled_2_player_name', 'fumbled_2_team',
       'fumble_recovery_1_team', 'fumble_recovery_1_yards',
       'fumble_recovery_1_player_id', 'fumble_recovery_1_player_name',
       'fumble_recovery_2_team', 'fumble_recovery_2_yards',
       'fumble_recovery_2_player_id', 'fumble_recovery_2_player_name',
       'sack_player_id', 'sack_player_name', 'half_sack_1_player_id',
       'half_sack_1_player_name', 'half_sack_2_player_id',
       'half_sack_2_player_name', 'return_team', 'return_yards',
       'penalty_team', 'penalty_player_id', 'penalty_player_name',
       'penalty_yards', 'replay_or_challenge',
       'replay_or_challenge_result', 'penalty_type',
       'defensive_two_point_attempt', 'defensive_two_point_conv',
       'defensive_extra_point_attempt', 'defensive_extra_point_conv',
       'safety_player_name', 'safety_player_id', 'season', 'cp', 'cpoe',
       'series', 'series_success', 'series_result', 'order_sequence',
       'start_time', 'time_of_day', 'stadium', 'weather', 'nfl_api_id',
       'play_clock', 'play_deleted', 'play_type_nfl',
       'special_teams_play', 'st_play_type', 'end_clock_time',
       'end_yard_line', 'fixed_drive', 'fixed_drive_result',
       'drive_real_start_time', 'drive_play_count',
       'drive_time_of_possession', 'drive_first_downs', 'drive_inside20',
       'drive_ended_with_score', 'drive_quarter_start',
       'drive_quarter_end', 'drive_yards_penalized',
       'drive_start_transition', 'drive_end_transition',
       'drive_game_clock_start', 'drive_game_clock_end',
       'drive_start_yard_line', 'drive_end_yard_line',
       'drive_play_id_started', 'drive_play_id_ended', 'away_score',
       'home_score', 'location', 'result', 'total', 'spread_line',
       'total_line', 'div_game', 'roof', 'surface', 'temp', 'wind',
       'home_coach', 'away_coach', 'stadium_id', 'game_stadium',
       'aborted_play', 'success', 'passer', 'passer_jersey_number',
       'rusher', 'rusher_jersey_number', 'receiver',
       'receiver_jersey_number', 'pass', 'rush', 'first_down', 'special',
       'play', 'passer_id', 'rusher_id', 'receiver_id', 'name',
       'jersey_number', 'id', 'fantasy_player_name', 'fantasy_player_id',
       'fantasy', 'fantasy_id', 'out_of_bounds', 'home_opening_kickoff',
       'qb_epa', 'xyac_epa', 'xyac_mean_yardage', 'xyac_median_yardage',
       'xyac_success', 'xyac_fd', 'xpass', 'pass_oe', 'nflverse_game_id',
       'possession_team', 'offense_formation', 'offense_personnel',
       'defenders_in_box', 'defense_personnel', 'number_of_pass_rushers',
       'players_on_play', 'offense_players', 'defense_players',
       'n_offense', 'n_defense'], dtype=object)

In [4]:
#This is a significantly large data set. We will find the number of columns we are dealing with:
num_columns = data.shape[1]
print(num_columns)

384

In [5]:
#There are 384 columns, and not all will be part of the modeling process. We will examine a little bit more on the data
data.head(20)

,play_id,game_id,old_game_id,home_team,away_team,season_type,week,posteam,posteam_type,defteam,...,offense_formation,offense_personnel,defenders_in_box,defense_personnel,number_of_pass_rushers,players_on_play,offense_players,defense_players,n_offense,n_defense
0,1.0,2001_01_ATL_SF,2001090900,SF,ATL,REG,1,None,None,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,35.0,2001_01_ATL_SF,2001090900,SF,ATL,REG,1,SF,home,ATL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,57.0,2001_01_ATL_SF,2001090900,SF,ATL,REG,1,SF,home,ATL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,78.0,2001_01_ATL_SF,2001090900,SF,ATL,REG,1,SF,home,ATL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,99.0,2001_01_ATL_SF,2001090900,SF,ATL,REG,1,SF,home,ATL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,124.0,2001_01_ATL_SF,2001090900,SF,ATL,REG,1,SF,home,ATL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,142.0,2001_01_ATL_SF,2001090900,SF,ATL,REG,1,SF,home,ATL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,163.0,2001_01_ATL_SF,2001090900,SF,ATL,REG,1,SF,home,ATL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,182.0,2001_01_ATL_SF,2001090900,SF,ATL,REG,1,SF,home,ATL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,205.0,2001_01_ATL_SF,2001090900,SF,ATL,REG,1,ATL,away,SF,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,226.0,2001_01_ATL_SF,2001090900,SF,ATL,REG,1,ATL,away,SF,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,245.0,2001_01_ATL_SF,2001090900,SF,ATL,REG,1,ATL,away,SF,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,271.0,2001_01_ATL_SF,2001090900,SF,ATL,REG,1,ATL,away,SF,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,289.0,2001_01_ATL_SF,2001090900,SF,ATL,REG,1,SF,home,ATL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,310.0,2001_01_ATL_SF,2001090900,SF,ATL,REG,1,SF,home,ATL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,331.0,2001_01_ATL_SF,2001090900,SF,ATL,REG,1,SF,home,ATL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,356.0,2001_01_ATL_SF,2001090900,SF,ATL,REG,1,SF,home,ATL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,375.0,2001_01_ATL_SF,2001090900,SF,ATL,REG,1,ATL,away,SF,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,400.0,2001_01_ATL_SF,2001090900,SF,ATL,REG,1,ATL,away,SF,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,421.0,2001_01_ATL_SF,2001090900,SF,ATL,REG,1,ATL,away,SF,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
data.sample(10)

,play_id,game_id,old_game_id,home_team,away_team,season_type,week,posteam,posteam_type,defteam,...,offense_formation,offense_personnel,defenders_in_box,defense_personnel,number_of_pass_rushers,players_on_play,offense_players,defense_players,n_offense,n_defense
383154,2632.0,2009_03_ATL_NE,2009092705,NE,ATL,REG,3,NE,home,ATL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
802532,1878.0,2017_15_GB_CAR,2017121701,CAR,GB,REG,15,CAR,home,GB,...,None,None,NaN,None,NaN,41465;44873;37635;39857;32386;42512;43975;4230...,00-0031001;00-0033903;00-0025580;00-0032922;00...,00-0028368;00-0029731;00-0031596;00-0031484;00...,11.0,11.0
355525,3203.0,2008_10_SF_ARI,2008111000,ARI,SF,REG,10,SF,away,ARI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
746115,3402.0,2016_12_LA_NO,2016112707,NO,LA,REG,12,NO,home,LA,...,I_FORM,"2 RB, 1 TE, 2 WR",8.0,"4 DL, 3 LB, 4 DB",7.0,30922;42356;26250;34500;30118;35585;41339;4141...,00-0024323;00-0032203;00-0020531;00-0027025;00...,00-0027745;00-0031393;00-0031394;00-0030527;00...,11.0,11.0
80945,3633.0,2002_14_CIN_CAR,2002120804,CAR,CIN,REG,14,CAR,home,CIN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
950704,4077.0,2020_16_SF_ARI,2020122601,ARI,SF,REG,16,SF,away,ARI,...,I_FORM,"2 RB, 1 TE, 2 WR",7.0,"3 DL, 4 LB, 4 DB",NaN,40078;46078;45069;44916;47816;30937;47848;4637...,00-0029892;00-0034847;00-0033221;00-0033936;00...,00-0035236;00-0024338;00-0035248;00-0029747;00...,11.0,11.0
996305,987.0,2021_16_BAL_CIN,2021122602,CIN,BAL,REG,16,BAL,away,CIN,...,SHOTGUN,"1 RB, 2 TE, 2 WR",8.0,"4 DL, 3 LB, 4 DB",4.0,47808;42721;46146;52642;43299;41222;44872;4522...,00-0035662;00-0031690;00-0030648;00-0034753;00...,00-0034834;00-0036432;00-0032379;00-0033548;00...,11.0,11.0
425106,229.0,2010_01_BAL_NYJ,2010091300,NYJ,BAL,REG,1,NYJ,home,BAL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1015248,3221.0,2022_03_PIT_CLE,2022092200,CLE,PIT,REG,3,CLE,home,PIT,...,SHOTGUN,"1 RB, 1 TE, 3 WR",8.0,"3 DL, 3 LB, 5 DB",NaN,46080;43297;44898;52418;54564;44870;44841;5287...,00-0033057;00-0033923;00-0036267;00-0037257;00...,00-0034789;00-0035971;00-0034514;00-0033930;00...,11.0,11.0
169080,788.0,2004_11_SF_TB,2004112109,TB,SF,REG,11,TB,home,SF,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
data.tail(10)

,play_id,game_id,old_game_id,home_team,away_team,season_type,week,posteam,posteam_type,defteam,...,offense_formation,offense_personnel,defenders_in_box,defense_personnel,number_of_pass_rushers,players_on_play,offense_players,defense_players,n_offense,n_defense
1057079,3947.0,2022_22_KC_PHI,2023021200,PHI,KC,POST,22,KC,away,PHI,...,SHOTGUN,"1 RB, 2 TE, 2 WR",6.0,"3 DL, 3 LB, 5 DB",NaN,46243;48516;47974;43367;46152;44874;40011;4618...,00-0034272;00-0032391;00-0034752;00-0033857;00...,00-0035386;00-0034993;00-0034375;00-0029653;00...,11.0,11.0
1057080,3979.0,2022_22_KC_PHI,2023021200,PHI,KC,POST,22,None,None,None,...,None,None,NaN,None,NaN,,,,0.0,0.0
1057081,3968.0,2022_22_KC_PHI,2023021200,PHI,KC,POST,22,KC,away,PHI,...,None,"1 RB, 3 TE, 1 WR",8.0,"3 DL, 3 LB, 5 DB",NaN,48516;46213;47974;43367;46152;40011;48683;4618...,00-0034386;00-0032391;00-0034752;00-0030506;00...,00-0035386;00-0034993;00-0034375;00-0029653;00...,11.0,11.0
1057082,4007.0,2022_22_KC_PHI,2023021200,PHI,KC,POST,22,None,None,None,...,None,None,NaN,None,NaN,,,,0.0,0.0
1057083,3996.0,2022_22_KC_PHI,2023021200,PHI,KC,POST,22,KC,away,PHI,...,None,"2 RB, 2 TE, 1 WR",6.0,"3 DL, 3 LB, 5 DB",NaN,48516;46213;47974;43367;46152;48683;46188;4132...,00-0034386;00-0032391;00-0034752;00-0035547;00...,00-0035386;00-0034993;00-0034375;00-0029653;00...,11.0,11.0
1057084,4035.0,2022_22_KC_PHI,2023021200,PHI,KC,POST,22,None,None,None,...,None,None,NaN,None,NaN,,,,0.0,0.0
1057085,4024.0,2022_22_KC_PHI,2023021200,PHI,KC,POST,22,KC,away,PHI,...,None,None,NaN,None,NaN,40994;46152;52618;54026;54478;53552;53492;5454...,00-0030615;00-0034752;00-0036230;00-0036623;00...,00-0036813;00-0037073;00-0036917;00-0037615;00...,11.0,11.0
1057086,4050.0,2022_22_KC_PHI,2023021200,PHI,KC,POST,22,PHI,home,KC,...,None,None,NaN,None,NaN,48259;54724;54568;54600;54026;53579;45102;4251...,00-0035157;00-0037198;00-0037819;00-0038043;00...,00-0036813;00-0036919;00-0033251;00-0036917;00...,11.0,11.0
1057087,4072.0,2022_22_KC_PHI,2023021200,PHI,KC,POST,22,PHI,home,KC,...,SHOTGUN,"1 RB, 1 TE, 3 WR",3.0,"0 DL, 4 LB, 7 DB",2.0,52608;52546;48259;46118;47846;43368;54568;5460...,00-0036271;00-0034351;00-0032954;00-0036919;00...,00-0036374;00-0035157;00-0035625;00-0037819;00...,11.0,11.0
1057088,4094.0,2022_22_KC_PHI,2023021200,PHI,KC,POST,22,None,None,None,...,None,None,NaN,None,NaN,,,,0.0,0.0

In [8]:
#Finding missing values organized by the count and its percentage with filled in information
missing = pd.concat([data.isnull().sum(), 100 * data.isnull().mean()], axis=1)
missing.columns=['count', '%']
missing.sort_values(by='%', ascending=False)

                                    count           %
drive_real_start_time             1057089  100.000000
lateral_sack_player_id            1057089  100.000000
lateral_sack_player_name          1057089  100.000000
tackle_with_assist_2_team         1057088   99.999905
tackle_with_assist_2_player_name  1057088   99.999905
...                                   ...         ...
no_huddle                               0    0.000000
qb_kneel                                0    0.000000
qb_spike                                0    0.000000
qb_scramble                             0    0.000000
play_id                                 0    0.000000

[384 rows x 2 columns]

In [9]:
#From the code above, there seems to be a lot of columns with a lot missing data. Lets see columns with more than 80% of its data missing:

missing_2 = pd.concat([data.isnull().sum(), 100 * data.isnull().mean()], axis=1)
missing_2.columns = ['count', '%']
missing_filtered = missing_2[missing_2['%'] >= 80.0]
missing_filtered.sort_values(by='%', ascending=False, inplace=True)
print(missing_filtered)

                                    count           %
lateral_sack_player_id            1057089  100.000000
drive_real_start_time             1057089  100.000000
lateral_sack_player_name          1057089  100.000000
tackle_with_assist_2_player_id    1057088   99.999905
tackle_with_assist_2_player_name  1057088   99.999905
...                                   ...         ...
assist_tackle_1_player_id          918402   86.880291
assist_tackle_1_player_name        918401   86.880196
assist_tackle_1_team               918401   86.880196
number_of_pass_rushers             911873   86.262651
yards_after_catch                  861775   81.523410

[108 rows x 2 columns]

/var/folders/2r/qvwb_49162s3q75v3pr4d1x00000gn/T/ipykernel_27444/407260728.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  missing_filtered.sort_values(by='%', ascending=False, inplace=True)

In [10]:
#It looks like there are 108 variables with more than 80% missing data.
missing_filtered.shape[:]

(108, 2)

In [11]:
#There may be important variables in the missing_filtered dataframe, so we will first drop the variables with more than 95% missing values

missing_3 = pd.concat([data.isnull().sum(), 100 * data.isnull().mean()], axis=1)
missing_3.columns = ['count', '%']
missing_filtered_2 = missing_3[missing_3['%'] >= 95.0]
missing_filtered_2.sort_values(by='%', ascending=False, inplace=True)
print(missing_filtered_2)

                                    count           %
drive_real_start_time             1057089  100.000000
lateral_sack_player_name          1057089  100.000000
lateral_sack_player_id            1057089  100.000000
tackle_with_assist_2_team         1057088   99.999905
tackle_with_assist_2_player_name  1057088   99.999905
...                                   ...         ...
timeout_team                      1012911   95.820787
tackle_for_loss_1_player_id       1009804   95.526867
tackle_for_loss_1_player_name     1009740   95.520812
qb_hit_1_player_id                1008132   95.368696
qb_hit_1_player_name              1008124   95.367940

[84 rows x 2 columns]

/var/folders/2r/qvwb_49162s3q75v3pr4d1x00000gn/T/ipykernel_27444/1326653706.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  missing_filtered_2.sort_values(by='%', ascending=False, inplace=True)

In [12]:
# Display all variable names without truncation
pd.set_option('display.max_rows', None)
print(missing_filtered_2)

                                        count           %
drive_real_start_time                 1057089  100.000000
lateral_sack_player_name              1057089  100.000000
lateral_sack_player_id                1057089  100.000000
tackle_with_assist_2_team             1057088   99.999905
tackle_with_assist_2_player_name      1057088   99.999905
tackle_with_assist_2_player_id        1057088   99.999905
assist_tackle_4_team                  1057086   99.999716
assist_tackle_4_player_name           1057086   99.999716
assist_tackle_4_player_id             1057086   99.999716
assist_tackle_3_team                  1057086   99.999716
assist_tackle_3_player_name           1057086   99.999716
assist_tackle_3_player_id             1057086   99.999716
tackle_for_loss_2_player_id           1057078   99.998959
tackle_for_loss_2_player_name         1057078   99.998959
lateral_rusher_player_id              1057048   99.996121
lateral_rushing_yards                 1057048   99.996121
lateral_rusher_player_name            1057048   99.996121
lateral_punt_returner_player_id       1057032   99.994608
lateral_punt_returner_player_name     1057032   99.994608
forced_fumble_player_2_player_name    1057022   99.993662
forced_fumble_player_2_player_id      1057022   99.993662
forced_fumble_player_2_team           1057022   99.993662
lateral_interception_player_name      1057017   99.993189
lateral_interception_player_id        1057017   99.993189
fumbled_2_player_id                   1056974   99.989121
fumbled_2_player_name                 1056974   99.989121
fumbled_2_team                        1056974   99.989121
fumble_recovery_2_player_id           1056971   99.988837
fumble_recovery_2_team                1056971   99.988837
fumble_recovery_2_yards               1056971   99.988837
fumble_recovery_2_player_name         1056971   99.988837
lateral_kickoff_returner_player_name  1056952   99.987040
lateral_kickoff_returner_player_id    1056952   99.987040
lateral_receiver_player_id            1056867   99.978999
lateral_receiver_player_name          1056867   99.978999
lateral_receiving_yards               1056867   99.978999
own_kickoff_recovery_player_name      1056858   99.978148
own_kickoff_recovery_player_id        1056858   99.978148
safety_player_id                      1056856   99.977958
safety_player_name                    1056851   99.977485
blocked_player_id                     1056140   99.910225
blocked_player_name                   1056139   99.910131
st_play_type                          1056073   99.903887
pass_defense_2_player_id              1055388   99.839086
pass_defense_2_player_name            1055388   99.839086
two_point_conv_result                 1055176   99.819031
qb_hit_2_player_id                    1054961   99.798692
qb_hit_2_player_name                  1054961   99.798692
half_sack_1_player_name               1054665   99.770691
half_sack_2_player_id                 1054665   99.770691
half_sack_2_player_name               1054665   99.770691
half_sack_1_player_id                 1054665   99.770691
solo_tackle_2_player_id               1051202   99.443093
solo_tackle_2_player_name             1051136   99.436850
solo_tackle_2_team                    1051131   99.436377
replay_or_challenge_result            1049068   99.241218
forced_fumble_player_1_player_id      1046258   98.975394
forced_fumble_player_1_player_name    1046231   98.972840
forced_fumble_player_1_team           1046230   98.972745
interception_player_name              1046127   98.963001
interception_player_id                1046127   98.963001
fumble_recovery_1_player_id           1042311   98.602010
fumble_recovery_1_player_name         1042311   98.602010
fumble_recovery_1_team                1042305   98.601442
fumble_recovery_1_yards               1042305   98.601442
fumbled_1_player_id                   1041023   98.480166
fumbled_1_player_name                 1041023   98.480166
fumbled_1_team                        1041020   98.479882
field_goal_result                     1034674   97.879554
sack_player_id                        1032692   97.692058
sack_player_name                      1032644   97.687517
extra_point_result                    1029627   97.402111
td_player_id                          1027596   97.209979
td_player_name                        1027593   97.209696
td_team                               1027593   97.209696
kickoff_returner_player_id            1020968   96.582975
kickoff_returner_player_name          1020967   96.582880
punt_returner_player_id               1019794   96.471915
punt_returner_player_name             1019791   96.471631
timeout_team                          1012911   95.820787
tackle_for_loss_1_player_id           1009804   95.526867
tackle_for_loss_1_player_name         1009740   95.520812
qb_hit_1_player_id                    1008132   95.368696
qb_hit_1_player_name                  1008124   95.367940

In [13]:
#defining a function that will drop the columns with a certain percentage of missing data: in this case, 95% or more

def drop_columns_with_high_missing_data(data, threshold=95.0):
    """
    Drop columns from the DataFrame that have more than a specified percentage of missing data.

    Parameters:
    - df: DataFrame
    - threshold: float, optional (default=80.0)
        The threshold percentage for missing data. Columns with missing data exceeding this threshold will be dropped.

    Returns:
    - df_cleaned: DataFrame
        The DataFrame with columns having more than the specified percentage of missing data dropped.
    - dropped_columns: list
        List of column names that were dropped.
    """
    # Calculating the percentage of missing data for each column
    missing = pd.concat([data.isnull().sum(), 100 * data.isnull().mean()], axis=1)
    missing.columns = ['count', '%']

    # Filtering columns with missing data exceeding the threshold
    missing_filtered = missing[missing['%'] >= threshold]
    dropped_columns = missing_filtered.index.tolist()

    # Dropping columns from the DataFrame
    data_cleaned = data.drop(columns=dropped_columns)

    # Printing information about dropped columns to know which ones were dropped
    if dropped_columns:
        print(f"Dropped Columns ({len(dropped_columns)}): {dropped_columns}")
    else:
        print("No columns dropped.")

    return data_cleaned, dropped_columns

In [14]:
data_cleaned, dropped_columns = drop_columns_with_high_missing_data(data, threshold=95.0)
print(data_cleaned)

Dropped Columns (84): ['field_goal_result', 'extra_point_result', 'two_point_conv_result', 'timeout_team', 'td_team', 'td_player_name', 'td_player_id', 'lateral_receiver_player_id', 'lateral_receiver_player_name', 'lateral_receiving_yards', 'lateral_rusher_player_id', 'lateral_rusher_player_name', 'lateral_rushing_yards', 'lateral_sack_player_id', 'lateral_sack_player_name', 'interception_player_id', 'interception_player_name', 'lateral_interception_player_id', 'lateral_interception_player_name', 'punt_returner_player_id', 'punt_returner_player_name', 'lateral_punt_returner_player_id', 'lateral_punt_returner_player_name', 'kickoff_returner_player_name', 'kickoff_returner_player_id', 'lateral_kickoff_returner_player_id', 'lateral_kickoff_returner_player_name', 'own_kickoff_recovery_player_id', 'own_kickoff_recovery_player_name', 'blocked_player_id', 'blocked_player_name', 'tackle_for_loss_1_player_id', 'tackle_for_loss_1_player_name', 'tackle_for_loss_2_player_id', 'tackle_for_loss_2_player_name', 'qb_hit_1_player_id', 'qb_hit_1_player_name', 'qb_hit_2_player_id', 'qb_hit_2_player_name', 'forced_fumble_player_1_team', 'forced_fumble_player_1_player_id', 'forced_fumble_player_1_player_name', 'forced_fumble_player_2_team', 'forced_fumble_player_2_player_id', 'forced_fumble_player_2_player_name', 'solo_tackle_2_team', 'solo_tackle_2_player_id', 'solo_tackle_2_player_name', 'assist_tackle_3_player_id', 'assist_tackle_3_player_name', 'assist_tackle_3_team', 'assist_tackle_4_player_id', 'assist_tackle_4_player_name', 'assist_tackle_4_team', 'tackle_with_assist_2_player_id', 'tackle_with_assist_2_player_name', 'tackle_with_assist_2_team', 'pass_defense_2_player_id', 'pass_defense_2_player_name', 'fumbled_1_team', 'fumbled_1_player_id', 'fumbled_1_player_name', 'fumbled_2_player_id', 'fumbled_2_player_name', 'fumbled_2_team', 'fumble_recovery_1_team', 'fumble_recovery_1_yards', 'fumble_recovery_1_player_id', 'fumble_recovery_1_player_name', 'fumble_recovery_2_team', 'fumble_recovery_2_yards', 'fumble_recovery_2_player_id', 'fumble_recovery_2_player_name', 'sack_player_id', 'sack_player_name', 'half_sack_1_player_id', 'half_sack_1_player_name', 'half_sack_2_player_id', 'half_sack_2_player_name', 'replay_or_challenge_result', 'safety_player_name', 'safety_player_id', 'st_play_type', 'drive_real_start_time']

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

#Determing the variables with assumingly higher significance levels with passing yards from external resources:

In [31]:
#With the significantly large amounts of data with the multitude of variables, I will create a list of variables that will help me build my model

columns = ['passer_player_name', 'posteam', 'defteam', 'season', 'week', 'home_team', 'away_team', 'play_type', 'air_yards', 
           'yards_after_catch', 'epa', 'complete_pass', 'incomplete_pass', 'interception', 'qb_hit', 'sack', 'pass_touchdown',
           'passing_yards', 'cpoe', 'roof', 'surface']

#None of these variables have been dropped
#We will create a new dataframe using only the columns 
qb_data = data[columns]

In [32]:
qb_data.head()

,passer_player_name,posteam,defteam,season,week,home_team,away_team,play_type,air_yards,yards_after_catch,...,complete_pass,incomplete_pass,interception,qb_hit,sack,pass_touchdown,passing_yards,cpoe,roof,surface
0,None,None,None,2001,1,SF,ATL,None,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,outdoors,grass
1,None,SF,ATL,2001,1,SF,ATL,kickoff,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,outdoors,grass
2,J.Garcia,SF,ATL,2001,1,SF,ATL,pass,NaN,NaN,...,1.0,0.0,0.0,0.0,0.0,0.0,6.0,NaN,outdoors,grass
3,None,SF,ATL,2001,1,SF,ATL,run,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,outdoors,grass
4,J.Garcia,SF,ATL,2001,1,SF,ATL,pass,NaN,NaN,...,1.0,0.0,0.0,0.0,0.0,0.0,26.0,NaN,outdoors,grass

In [33]:
#Checking what sorts of play_types there are 
qb_data[['play_type']].sample(20)

          play_type
530834          run
533142      kickoff
101665         pass
707611  extra_point
141053         pass
97050       no_play
341679      no_play
568123         None
78539          punt
166808          run
374229   field_goal
648918         punt
488012         pass
970745          run
515064         pass
754805      kickoff
396188      no_play
22072          pass
122548         punt
650028         pass

In [34]:
# Drop all rows that are not a pass because we are predicting qb_passing touchdowns
qb_data = qb_data[qb_data['play_type'] == 'pass']

# Drop the play type column
df = qb_data.drop(columns=['play_type'])

In [35]:
df.head()

,passer_player_name,posteam,defteam,season,week,home_team,away_team,air_yards,yards_after_catch,epa,complete_pass,incomplete_pass,interception,qb_hit,sack,pass_touchdown,passing_yards,cpoe,roof,surface
2,J.Garcia,SF,ATL,2001,1,SF,ATL,NaN,NaN,0.232765,1.0,0.0,0.0,0.0,0.0,0.0,6.0,NaN,outdoors,grass
4,J.Garcia,SF,ATL,2001,1,SF,ATL,NaN,NaN,2.373976,1.0,0.0,0.0,0.0,0.0,0.0,26.0,NaN,outdoors,grass
5,J.Garcia,SF,ATL,2001,1,SF,ATL,NaN,NaN,-0.474315,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,outdoors,grass
7,J.Garcia,SF,ATL,2001,1,SF,ATL,NaN,NaN,-2.309843,0.0,0.0,0.0,1.0,1.0,0.0,NaN,NaN,outdoors,grass
10,C.Chandler,ATL,SF,2001,1,SF,ATL,NaN,NaN,-1.340032,0.0,0.0,0.0,1.0,1.0,0.0,NaN,NaN,outdoors,grass

In [37]:
df.shape

(426927, 20)

In [38]:
qb_data.head()

,passer_player_name,posteam,defteam,season,week,home_team,away_team,play_type,air_yards,yards_after_catch,...,complete_pass,incomplete_pass,interception,qb_hit,sack,pass_touchdown,passing_yards,cpoe,roof,surface
2,J.Garcia,SF,ATL,2001,1,SF,ATL,pass,NaN,NaN,...,1.0,0.0,0.0,0.0,0.0,0.0,6.0,NaN,outdoors,grass
4,J.Garcia,SF,ATL,2001,1,SF,ATL,pass,NaN,NaN,...,1.0,0.0,0.0,0.0,0.0,0.0,26.0,NaN,outdoors,grass
5,J.Garcia,SF,ATL,2001,1,SF,ATL,pass,NaN,NaN,...,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,outdoors,grass
7,J.Garcia,SF,ATL,2001,1,SF,ATL,pass,NaN,NaN,...,0.0,0.0,0.0,1.0,1.0,0.0,NaN,NaN,outdoors,grass
10,C.Chandler,ATL,SF,2001,1,SF,ATL,pass,NaN,NaN,...,0.0,0.0,0.0,1.0,1.0,0.0,NaN,NaN,outdoors,grass

In [42]:
# Grouping the data together by passer, week, season and aggregate
passing_df = passer_data.groupby(['passer_player_name', 'week', 'season'], as_index=False).agg(
    {'posteam' : 'first',
     'defteam' : 'first',
     'home_team' : 'first',
     'away_team' : 'first',
     'air_yards' : 'sum',
     'yards_after_catch' : 'sum',
     'epa' : 'sum',
     'complete_pass' : 'sum',
     'incomplete_pass' : 'sum',
     'interception' : 'sum',
     'qb_hit' : 'sum',
     'sack' : 'sum',
     'pass_touchdown' : 'sum',
     'passing_yards' : 'sum',
     'cpoe' : 'mean',
     'roof' : 'first',
     'surface' : 'first'
     }
)

In [43]:
#checking to see the format
passing_df.head()

,passer_player_name,week,season,posteam,defteam,home_team,away_team,air_yards,yards_after_catch,epa,complete_pass,incomplete_pass,interception,qb_hit,sack,pass_touchdown,passing_yards,cpoe,roof,surface
0,A. Randle El,6,2003,PIT,DEN,DEN,PIT,0.0,0.0,-0.114645,1.0,0.0,0.0,0.0,0.0,0.0,4.0,NaN,outdoors,grass
1,A. Randle El,11,2003,PIT,SF,SF,PIT,0.0,0.0,-1.719602,1.0,0.0,0.0,0.0,0.0,0.0,-7.0,NaN,outdoors,grass
2,A. Van Pelt,8,2003,BUF,KC,KC,BUF,0.0,0.0,-5.139258,2.0,0.0,2.0,0.0,0.0,0.0,12.0,NaN,outdoors,grass
3,A. Van Pelt,12,2002,BUF,NYJ,NYJ,BUF,0.0,0.0,-0.197210,2.0,0.0,0.0,0.0,0.0,0.0,5.0,NaN,outdoors,grass
4,A.Andrews,14,2015,TEN,NYJ,NYJ,TEN,26.0,15.0,3.954364,1.0,0.0,0.0,0.0,0.0,1.0,41.0,66.256546,outdoors,fieldturf

In [44]:
#storing it so I can use it for the next process
passing_df.to_csv('passing_data_cleaned.csv', index=False)